import mongoose from "mongoose";

const familySchema = new mongoose.Schema({
    status:{
        type:Boolean,
        default:false
    },
    samagraId:{
        type:String,
        required:true
    },
    name:{
        type:String,
        required:true
    },
    fatherName:{
        type:String,
        required:true
    },
    dob:{
        type:String,
        required:true
    },
    gender:{
      type:String,
      required:true
    },
    maritalStatus:{
        type:String,
        required:true
    },
    education:{
        type:String,
        required:true
    },
    occupation:{
        type:String,
        required:true
    },
    contact:{
        type:String,
        required:true
    },
    familyMembers:{
        type:String,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    family:[{
        member_name:{
            type:String,
            required:true
        },
        member_fatherName:{
            type:String,
            required:true
        },
        gender:{
            type:String,
            required:true
          },
        member_dob:{
            type:String,
            required:true
        },
        member_maritalStatus:{
            type:String,
            required:true
        },
        member_relative:{
            type:String,
            required:true
        }
    }]
})

export const Family = mongoose.model("family",familySchema);